#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Do this to make Java Apps work with XMonad (Fiji & ImageJ)
export _JAVA_AWT_WM_NONREPARENTING=1

# Configure X
xsetroot -solid "#000000" -cursor_name left_ptr &
xrdb -merge ~/.Xresources &

# qtconfig needs this set to pick up gtk theme settings
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Automatically mount removable media
thunar --daemon &

# Start the system tray
#trayer --edge-top --align-right --expand true --widthtype percent --width 5 &

#exec dbus-launch ck-launch-session --exit-with-session xmonad
exec xmonad
